### ISSUE TITLE
open source container review

### ISSUE THREAD

**Issue by vsoch** [openjournals/openjournals.github.io#1]
hey @arfon ! I just had a great idea, why not offer peer review for containers? Then I realized this is similar to the JOSS effort, and I went to your base url for inspection, and found that you have more than one journal!

What are your thoughts on an open source journal for container review? The same format on Github and with repos (and badges) is just right. There is so much that needs to be checked for container quality, everything from usage to runtime to (importantly) security vulnerabilities and testing. Linux containers (Singularity, Docker) are a very specific, special flavor of software. This would also help to define and provide for use a set of basic tests.

I would like to spear head a containers.theoj.org effort to handle the review, and take care of documentation, recruiting and getting things set up. What do you think?

**Comment by vsoch** [comment]
hey @arfon @kyleniemeyer @stuartlynn @physicsdavid @whedon I'm posting here again because I haven't gotten a response from any avenue, the [docs here](http://www.theoj.org/) indicate this is the correct issue board, and it's been quite some time since I posted this :( No worries, I know you must be busy! I'm still positive and excited about this!

We have built up energy for containers, specifically even for behavioral experiments, and I'd really like to get one (officially) started via the openjournals organization. As I mentioned in [this issue](https://github.com/FelixHenninger/lab.js/issues/17) we would have a publication flow that goes from:

```bash
experiment(s) design --> build and deploy --> publication submission --> peer review --> publication
```

We now have the first half of that pipeline done and ready to go - an experiment can be commit to Github and the verisoned container is deployed. And so the next step is establishing a place to submit, and then a template to programatically do it, which I don't think should be too hard. I can do all the PR, development, and whatever else is needed - there is a significant need and community behind this so I'd really like to get discussion going, at least! Can you please respond? I'm cc-ing  @felixHenninger and @jodeleeuw and @tylerburleigh, we develop the big projects for LabJs, jsPsych, and the Experiment Factory that are coming together to form the basis of this tooling.

**Comment by arfon** [comment]
:wave: @vsoch - apologies for the slow reply. I saw the conversation over in https://github.com/FelixHenninger/lab.js/issues/17 but was about to head out on vacation (which I'm now returned from) and didn't get a chance to reply.

I'd be happy to pick up this conversation again - perhaps we could do a video chat sometime as a group to talk more about this?

**Comment by vsoch** [comment]
Yes definitely! I was just chatting about this with @jodeleeuw, and I'm just missing the CogSci conference in Madison this week, so we thought that a video chat might be a good first one. And I think we are switching spots in terms of vacation because I'm going to be in Pittsburgh this week on travel, then a wedding!

But let's put something down for right after that? How about sometime the week of August 13th? I'm in Eastern time now (same as @jodeleeuw I think) and @felixhenninger is in Germany (6 hours ahead I think?) (and you are in Baltimore?) so likely a good squishy spot would be mid morning for East coasters corresponding to hit mid or later afternoon in Germany, unless Felix has a schedule where he would want to go home first and do an evening. Is there a particular day that would work best for everyone? I could do any of those days, and my preference would be Tues 8/14 - Thurs 8/16.

**Comment by vsoch** [comment]
okay looks like @jodeleeuw is on vacation August 3-18 - let's say starting Monday, August 20th onward!

**Comment by FelixHenninger** [comment]
This sounds awesome, count me in!

**Comment by vsoch** [comment]
Awesome! And @FelixHenninger you mentioned the week of  August 20th, and the 24th work for you as well to chat?

**Comment by arfon** [comment]
Closing as stale.

**Comment by vsoch** [comment]
Sorry I should have closed this in 2018 when you let me know you didn’t have bandwidth for the project @arfon. We couldn’t have done it without you. Thanks for closing!
