### ISSUE TITLE
Proposal of new journal - OpenFOAM

### ISSUE THREAD

**Issue by jmnobrega** [openjournals/openjournals.github.io#7]
Dear Sirs,

My name is João Miguel Nóbrega, and I am Associate Professor at the University of Minho, in Portugal. My main area of activity is computational modelling, and, since 2014, most of the developments from my group are being performed with the support of the computational library OpenFOAM (www.openfoam.com). 

OpenFOAM (Open source Field Operation And Manipulation) is a free, open source computational toolbox that has a large user base across most areas of engineering and science, from both commercial and academic organizations. As a technology, OpenFOAM® provides an extensive range of features to solve anything from complex fluid flows involving chemical reactions, turbulence and heat transfer, to solid dynamics and electromagnetics, among several others. Additionally, the OpenFOAM® technology offers complete freedom to customize and extend its functionalities. These features have been assuring, since its foundation, a constant increase of capabilities, covered areas and number of users all over the world.

The impact of OpenFOAM is significant in the computational modelling community. Currently there are two major annual conferences directly related to it: the OpenFOAM Workshop  (www.openfoamworkshop.org) and the OpenFOAM Conference (https://www.esi-group.com/company/events/2019/7th-openfoam-conference-2019). I was the host of the 11th OpenFOAM Workshop (ofw11.foam.pt), which took place in 2016, in Portugal. The following movie https://www.facebook.com/watch/?v=267548143613474 provides a summary of that event, and some additional insights about OpenFOAM. Moreover, I am the editor of a book published by Springer related to the 11th OpenFOAM Workshop (https://www.springer.com/gp/book/9783319608457), published in January 2019, which has more than 30,000 downloads.

The owner of OpenFOAM trademark is ESI Group (https://www.esi-group.com/), which has been doing a huge effort to organize the community of users/developers and recently started a new governance model (https://www.openfoam.com/governance/), that comprises the Steering (https://www.openfoam.com/governance/steering-committee.php) and several Technical (https://www.openfoam.com/governance/technical-committees.php) committees. I am a member on the Documentation Technical Committee (https://wiki.openfoam.com/Tutorials#Committee_Members_of_Documentation_and_Tutorial), which is in charge of the OpenFOAM Tutorial website (https://wiki.openfoam.com).

In the framework of the Documentation Committee we are currently discussing the creation of a journal, which should be the preferential forum to publish/disseminate OpenFOAM developments and new features.

We expect that the Journal follows the same approach of OpenFOAM, being free access, and with null or minimal publishing costs.

The main purpose of this contact is to figure out if there are chances to have a new OpenFOAM journal published by Open Journals.

Best wishes,

João Miguel Nóbrega
 
####################################
Associate Professor
IPC / i3N - Institute for Polymers and Composites Polymer Engineering Department Universidade do Minho Campus de Azurém
4800-058 Guimarães
Portugal

Tel (+351) 253510320
 
https://orcid.org/0000-0002-5303-6467?lang=en
http://www.researcherid.com/rid/G-1825-2011
http://scholar.google.pt/citations?user=s5nLHBsAAAAJ
http://www.ipc.uminho.pt/
http://www.dep.uminho.pt/
 
CIÊNCIA ID DD14-7E8A-7F7E

**Comment by arfon** [comment]
> In the framework of the Documentation Committee we are currently discussing the creation of a journal, which should be the preferential forum to publish/disseminate OpenFOAM developments and new features.

Hi @jmnobrega, thanks for getting in touch. This is an interesting idea and I thunk we'd definitely be interested in hearing more about this. 

On the face of it, this sounds like a fairly narrow scope for a whole new journal but I may be misunderstanding the scale/scope here of what you're thinking.

My suggestion would be that we try and have a conversation about this on Skype/Hangouts etc. sometime so I can ask more questions.

Please send me a followup message at arfon.smith@gmail.com to continue conversations.
